"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IRewarder__factory = void 0;
var ethers_1 = require("ethers");
var IRewarder__factory = /** @class */ (function () {
    function IRewarder__factory() {
    }
    IRewarder__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    return IRewarder__factory;
}());
exports.IRewarder__factory = IRewarder__factory;
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "pid",
                type: "uint256"
            },
            {
                internalType: "address",
                name: "user",
                type: "address"
            },
            {
                internalType: "address",
                name: "recipient",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "beetsAmount",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "newLpAmount",
                type: "uint256"
            },
        ],
        name: "onBeetsReward",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "pid",
                type: "uint256"
            },
            {
                internalType: "address",
                name: "user",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "beetsAmount",
                type: "uint256"
            },
        ],
        name: "pendingTokens",
        outputs: [
            {
                internalType: "contract IERC20[]",
                name: "",
                type: "address[]"
            },
            {
                internalType: "uint256[]",
                name: "",
                type: "uint256[]"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
